### ISSUE TITLE
Repo fails to open each time I launch. Errors in terminal.

### ISSUE THREAD

**Issue by brittyazel** [flathub/com.axosoft.GitKraken#183]
Each time I launch GitKraken my repo fails to open, the error reads "Open Failed - Could not find a compatible repository at <foo>". This happens every single launch to the last open repo, and re-opening it works for the remainder of that session.

Looking at the chat logs I see these errors which seem pretty major:

```
[2:0501/135444.099885:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0501/135444.099910:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
ldd: warning: you do not have execution permission for `/app/extra/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-ubuntu-18.node'
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `gitkraken --trace-deprecation ...` to show where the warning was created)
(node:2) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
state:  unavailable
(node:2) UnhandledPromiseRejectionWarning: Error: Could not read response
    at fetchGitHubEnterpriseMetadataSaga (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:758370)
    at fetchGitHubEnterpriseMetadataSaga.next (<anonymous>)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706915)
    at currCb (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at pe.<computed> (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4702062)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706471
    at digestEffect (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707543)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706980)
    at proc (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706688)
    at pe.<computed> (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4702019)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706471
    at digestEffect (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707543)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706980)
    at Object.currCb [as cont] (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at end (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705646)
    at D.cont (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705144)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:2) UnhandledPromiseRejectionWarning: Error: Could not read response
    at fetchGitHubEnterpriseMetadataSaga (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:758370)
    at fetchGitHubEnterpriseMetadataSaga.next (<anonymous>)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706915)
    at currCb (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at pe.<computed> (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4702062)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706471
    at digestEffect (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707543)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706980)
    at proc (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706688)
    at pe.<computed> (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4702019)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706471
    at digestEffect (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707543)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706980)
    at Object.currCb [as cont] (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at end (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705646)
    at D.cont (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705144)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
ldd: warning: you do not have execution permission for `/app/extra/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-ubuntu-18.node'
Error: 2
    at handleError (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:111542)
    at handleError.next (<anonymous>)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706915)
    at proc (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706688)
    at pe.<computed> (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4702019)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706471
    at digestEffect (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707543)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706980)
    at Object.currCb [as cont] (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at end (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705646)
    at abort (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705007)
    at D.cont (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705102)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707059)
    at currCb (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4700617
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
The above error occurred in task call

(node:2) UnhandledPromiseRejectionWarning: Error: 2
    at handleError (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:111542)
    at handleError.next (<anonymous>)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706915)
    at proc (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706688)
    at pe.<computed> (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4702019)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706471
    at digestEffect (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707543)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706980)
    at Object.currCb [as cont] (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at end (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705646)
    at abort (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705007)
    at D.cont (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705102)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707059)
    at currCb (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4700617
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:2) UnhandledPromiseRejectionWarning: Error: 2
    at handleError (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:111542)
    at handleError.next (<anonymous>)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706915)
    at proc (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706688)
    at pe.<computed> (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4702019)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706471
    at digestEffect (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707543)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706980)
    at Object.currCb [as cont] (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at end (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705646)
    at abort (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705007)
    at D.cont (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705102)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707059)
    at currCb (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4700617
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:2) UnhandledPromiseRejectionWarning: Error: 2
    at handleError (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:111542)
    at handleError.next (<anonymous>)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706915)
    at proc (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706688)
    at pe.<computed> (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4702019)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706471
    at digestEffect (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707543)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706980)
    at Object.currCb [as cont] (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at end (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705646)
    at abort (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705007)
    at D.cont (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705102)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707059)
    at currCb (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4700617
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:2) UnhandledPromiseRejectionWarning: Error: 2
    at handleError (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:111542)
    at handleError.next (<anonymous>)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706915)
    at proc (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706688)
    at pe.<computed> (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4702019)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706471
    at digestEffect (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707543)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706980)
    at Object.currCb [as cont] (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at end (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705646)
    at abort (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705007)
    at D.cont (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705102)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707059)
    at currCb (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4700617
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:2) UnhandledPromiseRejectionWarning: Error: 2
    at handleError (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:111542)
    at handleError.next (<anonymous>)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706915)
    at proc (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706688)
    at pe.<computed> (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4702019)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706471
    at digestEffect (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707543)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4706980)
    at Object.currCb [as cont] (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at end (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705646)
    at abort (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705007)
    at D.cont (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4705102)
    at next (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707059)
    at currCb (/app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4707305)
    at /app/extra/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:4700617
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
ldd: warning: you do not have execution permission for `/app/extra/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-ubuntu-18.node'
state:  checking
(node:164) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)
(node:164) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
state:  unavailable
[41:0501/135448.555323:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
(node:164) DeprecationWarning: Instantiation of DiffOptions is deprecated and will be removed in an upcoming version
(node:164) DeprecationWarning: Use NodeGit.Credential.userpassPlaintextNew instead of NodeGit.Cred.userpassPlaintextNew
[41:0501/135457.558071:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
```

I'm not sure if any of these errors are specific to the Flatpak itself or GitKraken as a whole, so apologies if this is the wrong spot.

**Comment by Lctrs** [comment]
Maybe try to reset the app by deleting the directory `~/.var/app/com.axosoft.GitKraken`. This will delete all your configuration, etc.

**Comment by brittyazel** [comment]
Yep, that was the first thing I tried. No luck unfortunately.
